<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_penjualan_model extends CI_Model
{

    public $table = 'tbl_penjualan';
    public $id = 'id_penjualan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_customer', 'tbl_customer.id_customer = tbl_penjualan.id_customer');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_tanggal($awal, $akhir)
    {
        $this->db->join('tbl_customer', 'tbl_customer.id_customer = tbl_penjualan.id_customer');
        $this->db->where("tanggal_penjualan BETWEEN '$awal' AND '$akhir'");
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_customer', 'tbl_customer.id_customer = tbl_penjualan.id_customer');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_detail_by_id($id)
    {
        $this->db->join('tbl_sparepart' , 'tbl_sparepart.id_sparepart = tbl_detail_penjualan.id_sparepart');
        $this->db->where($this->id, $id);
        return $this->db->get('tbl_detail_penjualan')->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penjualan', $q);
        $this->db->or_like('id_customer', $q);
        $this->db->or_like('jenis_pembayaran', $q);
        $this->db->or_like('tanggal_penjualan', $q);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penjualan', $q);
        $this->db->or_like('id_customer', $q);
        $this->db->or_like('jenis_pembayaran', $q);
        $this->db->or_like('tanggal_penjualan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function delete_detail($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete('tbl_detail_penjualan');
    }
}

/* End of file Tbl_penjualan_model.php */
/* Location: ./application/models/Tbl_penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-06-13 08:16:33 */
/* http://harviacode.com */