<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pembelian_model extends CI_Model
{

    public $table = 'tbl_pembelian';
    public $id = 'id_pembelian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_sparepart', 'tbl_pembelian.id_sparepart = tbl_sparepart.id_sparepart');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_tanggal($awal, $akhir)
    {
        $this->db->join('tbl_sparepart', 'tbl_pembelian.id_sparepart = tbl_sparepart.id_sparepart');
        $this->db->order_by($this->id, $this->order);
        $this->db->where("tanggal_pembelian BETWEEN '$awal' AND '$akhir'");
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pembelian', $q);
        $this->db->or_like('id_sparepart', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('supplier', $q);
        $this->db->or_like('tanggal_pembelian', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pembelian', $q);
        $this->db->or_like('id_sparepart', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('supplier', $q);
        $this->db->or_like('tanggal_pembelian', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_pembelian_model.php */
/* Location: ./application/models/Tbl_pembelian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-06-11 13:22:53 */
/* http://harviacode.com */